Import Debian changes 1.08.0-6
insserv (1.08.0-6) unstable; urgency=low

  * Minor change to the template text, explaining that the S* symlinks
    are renamed to K* symlinks in rc0.d/ and rc6.d/.
  * Correct override file for sysklogd and klogd.  These should not
    start in runlevel S, and should stop in runlevel 1.
  * Add $syslog to the dependency list for openbsd-inetd, to make sure
    it can log its start to syslog.  Drop $local_fs, as it is a
    dependency for $remote_fs.
  * New patch debian/patches/40_nosusescript to avoid inserting the
    'single' script showing up in runlevel S, and also avoid fixing
    the sequence number to the values used by SuSe.
  * Correct override file for hotplug-net, it should depend on $local_fs.
  * Correct override file for hotplut, it should stop before $local_fs.
  * Modify patch 31_debian_conf to also list ifupdown as part of the
    $network facility, to make $network available in runlevel 0 and 6.
  * Try to make update-bootsystem-insserv more robust on restores.
    Move conversion logs and related files to /var/lib/insserv.

diff --git a/debian/insserv.postinst b/debian/insserv.postinst
--- a/debian/insserv.postinst
+++ b/debian/insserv.postinst
@@ -28,38 +28,45 @@ check_divert() {
     esac
 }
 
+enable_insserv() {
+    # Reorder the boot sequence, and divert update-rc.d if it worked
+    if update-bootsystem-insserv ; then
+	: # All OK
+	echo "success: Boot system successfully converted"
+	touch $flagfile
+
+        # Divert update-rc.d to update-rc.d-insserv
+	check_divert true /usr/sbin/update-rc.d \
+	    /usr/sbin/update-rc.d-insserv
+    else
+	echo "error: Unable to enable dependency based boot system."
+    fi
+}
+
+disable_insserv() {
+    echo "info: Disabling dependency based boot system"
+    # Undo divert
+    check_divert false /usr/sbin/update-rc.d \
+	/usr/sbin/update-rc.d-insserv
+
+    # Revert to old boot order if possible
+    update-bootsystem-insserv restore
+
+    rm -f $flagfile
+}
+
 case "$1" in
     configure)
 
 	# Only enable this code if environment variable
 	# BAD_INSSERV_HACKER=true is set
-	[ true = "$BAD_INSSERV_HACKER" ] || break
-
-	db_get insserv/enable || true
-	if [ true = "$RET" ] && [ ! -f $flagfile ]; then
-	    # Enable it, as it was not enabled already
-
-	    # Reorder the boot sequence, and divert update-rc.d if it worked
-	    if update-bootsystem-insserv ; then
-		: # All OK
-		echo "success: Boot system successfully converted"
-		touch $flagfile
-
-	        # Divert update-rc.d to update-rc.d-insserv
-		check_divert true /usr/sbin/update-rc.d \
-		    /usr/sbin/update-rc.d-insserv
-	    else
-		echo "error: Unable to enable dependency based boot system."
+        if [ true = "$BAD_INSSERV_HACKER" ] ; then
+	    db_get insserv/enable || true
+	    if [ true = "$RET" ] && [ ! -f $flagfile ]; then
+		enable_insserv # Enable it, as it was not enabled already
+	    elif [ true != "$RET" ] && [ -f $flagfile ] ; then
+		disable_insserv
 	    fi
-	elif [ true != "$RET" ] && [ -f $flagfile ] ; then # Disable it
-	    # Undo divert
-	    check_divert false /usr/sbin/update-rc.d \
-		/usr/sbin/update-rc.d-insserv
-
-	    # Revert to old boot order if possible
-	    update-bootsystem-insserv restore
-
-	    rm -f $flagfile
 	fi
 	;;
     *)
diff --git a/debian/update-bootsystem-insserv b/debian/update-bootsystem-insserv
--- a/debian/update-bootsystem-insserv
+++ b/debian/update-bootsystem-insserv
@@ -8,15 +8,17 @@
 set -e
 
 now=`date +%Y%m%dT%H%M`
-logdir=/var/log
-backupfile="$logdir/insserv-bootscripts-$now.tar.gz"
-logfile="$logdir/insserv-run-$now.log"
+logdir=/var/lib/insserv
+backupfile="$logdir/bootscripts-$now.tar.gz"
+listfile="$logdir/bootscripts-$now-after.list"
+logfile="$logdir/run-$now.log"
+flagfile="$logdir/using-insserv"
 
 # Make sure insserv is in path
 PATH=/sbin:$PATH
 
 convert_rc_s_to_k() {
-  runlevel=$1 # Use level N to disable on all levels
+  runlevel=$1
   for link in $(cd $target/etc/rc$runlevel.d; ls S* || true); do
       set `echo $link|sed "s%S\(..\)\(.*\)%\1 \2%"`
       seq=$1
@@ -26,14 +28,41 @@ convert_rc_s_to_k() {
 }
 
 if [ restore = "$1" ] ; then
-    for backup in $logdir/insserv-bootscripts-*.tar.gz ; do
-	file=$backup
+    if [ ! -f $flagfile ] ; then
+	echo "error: The boot system is not currently converted to insserv."
+	echo "error: Flag file $flagfile is missing."
+	echo "error: Unable to remove the use of insserv."
+	exit 1
+    fi
+
+    # Check if there has been changes, or if it is safe to restore
+    # from backup
+
+    # Pick the last list of symlinks.
+    for file in $logdir/bootscripts-*-after.list ; do
+	listfile=$file
     done
-    if [ -f "$file" ] ; then
-	(cd /etc; rm -rf init.d rc*.d; tar zxf $file)
-	echo "info: successfully restored backup of init.d scripts"
+    ls /etc/init.d /etc/rc*.d > "$logdir/current.list"
+
+    # If the rc.d scripts order look like it did when we converted, it
+    # is safe to restore.
+    if [ -f $listfile ] && cmp $logdir/current.list $listfile ; then
+	rm "$logdir/current.list"
+	echo "info: Restoring using backed up copy of init.d/ and rc*.d/."
+	for backup in $logdir/bootscripts-*.tar.gz ; do
+	    backupfile=$backup
+	done
+	if [ -f "$backupfile" ] ; then
+	    (cd /etc; rm -rf init.d rc*.d; tar zxf $backupfile)
+	    echo "info: successfully restored backup of init.d scripts"
+	    rm $flagfile
+	else
+	    echo "error: Unable to locate backup file"
+	    exit 1
+	fi
     else
-	echo "error: Unable to locate backup file"
+	rm "$logdir/current.list"
+	echo "error: Unable to restore the boot sequence.  Invalid backup."
 	exit 1
     fi
 else
@@ -59,7 +88,11 @@ else
 	insserv -v
     ) > $logfile 2>&1
 
+    echo "info: Recording new boot sequence in $listfile"
+    ls /etc/init.d /etc/rc*.d > $listfile
+
     echo "info: Use '$0 restore' to restore the old boot sequence."
+    touch $flagfile
 fi
 
 exit 0
