Import Debian changes 1.09.0-13
insserv (1.09.0-13) unstable; urgency=low

  * Update patch 21_overrides to fix bug in override handling.  Now a
    header in a script or override file complete replaces previously
    loaded headers.
  * Add test to check and verify that override files in
    /etc/insserv/override replaces headers in the scripts in
    /etc/init.d/, and made previously failing loop breaking test
    fatal, as it is working with the fixed override patch.

diff --git a/debian/run-testsuite b/debian/run-testsuite
--- a/debian/run-testsuite
+++ b/debian/run-testsuite
@@ -54,6 +54,15 @@ test_order() {
     fi
 }
 
+on_exit() {
+    rm -rf $tmpdir
+}
+trap on_exit EXIT # Enable cleanup handler
+
+echo
+echo "info: test normal boot sequence scripts, and their order"
+echo
+
 cat <<'EOF' > $insconf
 $local_fs       +mountall +umountfs
 $network        +networking +ifupdown
@@ -351,11 +360,58 @@ check_order 6 umountroot reboot
 check_order 6 umountroot kexec
 check_order 6 kexec reboot
 
+echo
+echo "info: test if override files replace headers in the file"
+echo
 rm -rf $initddir
+mkdir -p $initddir
+
+# Two scripts with a loop between them
+insertscript base <<'EOF' || true
+### BEGIN INIT INFO
+# Provides:          base
+# Required-Start:
+# Required-Stop:
+# Default-Start:     S
+# Default-Stop:
+### END INIT INFO
+EOF
+
+insertscript mover <<'EOF' || true
+### BEGIN INIT INFO
+# Provides:          mover
+# Required-Start:    base
+# Required-Stop:
+# Default-Start:     S
+# Default-Stop:
+### END INIT INFO
+EOF
+
+check_order S base mover
+
+mkdir -p $overridedir
+cat <<'EOF' > $overridedir/mover
+### BEGIN INIT INFO
+# Provides:          mover
+# Required-Start:
+# Required-Stop:
+# X-Start-Before:    base
+# Default-Start:     S
+# Default-Stop:
+### END INIT INFO
+EOF
+
+insserv_reg mover
+
+(cd $tmpdir && ls *)
+
+# Make sure the override file moved mover before base
+check_order S mover base
 
 echo
 echo "info: testing to insert scripts with a loop"
 echo
+rm -rf $initddir
 mkdir -p $initddir
 
 # Two scripts with a loop between them
@@ -394,16 +450,18 @@ EOF
 insserv_reg loop1 || true
 insserv_reg loop2 || true
 
-# XXX This do not work yet, as the override file seem to be ignored
-test_order S loop1 loop2
+check_order S loop1 loop2
 
-# Test fake loop.  The loop is in the combined start and stop
-# sequence.  There is no loop in the start sequence, and no loop in
-# the stop sequence, but in the combined graph insserv is creating
-# internally, there is a loop.  This make sense, as scripts need to be
-# installed in dependency order, and there is no way to install these
-# scripts that make sure both start and stop dependencies are
-# fulfilled.
+# Test real loop in the combined start and stop sequence.  There is no
+# loop in the start sequence, and no loop in the stop sequence, but in
+# the combined graph insserv is creating internally, there is a loop.
+# This make sense, as scripts need to be installed in dependency
+# order, and there is no way to install these scripts that make sure
+# both start and stop dependencies are fulfilled.
+echo
+echo "info: test handling of loops in the combination of start and stop sequences"
+echo
+
 rm -rf $initddir
 mkdir -p $initddir
 
@@ -435,6 +493,10 @@ test_order 6 startsecond startfirst
 # Test another fake loop.  This one should work, as it is possible to
 # install the two scripts in sequence because one of the dependencies
 # are optional.  It does not with insserv today.
+echo
+echo "info: test handling of 'fake' loops in the combination of start and stop sequences"
+echo
+
 rm -rf $initddir
 mkdir -p $initddir
 
@@ -468,6 +530,10 @@ EOF
 # with insserv today.  Note thought that the generated order is
 # different from the one above.
 
+echo
+echo "info: test handling of 'fake' loops using reverse depends"
+echo
+
 rm -rf $initddir
 mkdir -p $initddir
 
@@ -498,8 +564,6 @@ EOF
 # will fail.  Making the tests non-fatal because of this.
 test_order S startfirst_stopfirst startsecond_stoplast
 test_order 6 startfirst_stopfirst startsecond_stoplast 
-
-rm -rf $tmpdir
 
 if [ 0 != $retval ] ; then
     echo "error: one or more test failed."
