Import Debian changes 1.09.0-11
insserv (1.09.0-11) unstable; urgency=low

  * Added test to demonstrate the fake loop warning issue (bug
    #458582).
  * Implemented support for non-fatal tests in the testsuite.
  * Added override file for dmraid, scsitools-pre.sh and scsitools.sh.
  * Added patch 44_reportloopmemb to make loop reporting code in
    insserv more helpful, and make sure to report the extended loop
    output in update-bootsystem-insserv when refusing to switch to
    dependency based boot (Closes: #458683).
  * Move code to divert update-rc.d from postinst to
    update-bootsystem-insserv, to make sure both ways to activate
    insserv are equivalent.
  * Extended check-initd-order to graph services with multiple
    provides as two nodes that depend on each other, and which ahve
    the same dependencies.
  * Changed update-bootsystem-insserv to call 'reset' after looping
    over packages postinst scripts, in case the terminal is messed up
    as it is when I test it.
  * Disabled check for reverse dependencies in check-initd-order.  It
    does not to work properly, and gave false error reports.
  * Removed flag file /etc/update-rc.d-insserv and use the update-rc.d
    diversion as the flag to detect if insserv is enabled.  Adjustd
    package removal and update-rc.d-insserv to reflect this.
  * Added Vcs-Svn and Vcs-Browser info in control file, pointing to
    the Debian packaging project.

diff --git a/debian/run-testsuite b/debian/run-testsuite
--- a/debian/run-testsuite
+++ b/debian/run-testsuite
@@ -28,14 +28,29 @@ insertscript() {
     insserv_reg $scriptname
 }
 
-check_order() {
+order_ok() {
     runlevel=$1
     script1=$2
     script2=$3
     order="$(echo $(cd $tmpdir/rc$runlevel.d/; ls *$script1 *$script2 2>/dev/null | sed 's/[SK]..//') )"
     if [ "$order" != "$script1 $script2" ] ; then
+	return 0
+    fi
+    return 1;
+}
+
+# Fatal check
+check_order() {
+    if order_ok $@ ; then
 	echo "error: incorrect $runlevel sequence $script1 not before $script2"
 	retval=1
+    fi
+}
+
+# Non-fatal check
+test_order() {
+    if order_ok $@ ; then
+	echo "warning: incorrect $runlevel sequence $script1 not before $script2"
     fi
 }
 
@@ -360,7 +375,76 @@ insserv_reg loop1 || true
 insserv_reg loop2 || true
 
 # XXX This do not work yet, as the override file seem to be ignored
-#check_order S loop1 loop2
+test_order S loop1 loop2
+
+# Test fake loop.  The loop is in the combined start and stop
+# sequence.  There is no loop in the start sequence, and no loop in
+# the stop sequence, but in the combined graph insserv is creating
+# internally, there is a loop.  This make sense, as scripts need to be
+# installed in dependency order, and there is no way to install these
+# scripts that make sure both start and stop dependencies are
+# fulfilled.
+rm -rf $initddir
+mkdir -p $initddir
+
+insertscript startfirst <<'EOF' || true
+### BEGIN INIT INFO
+# Provides:          startfirst
+# Required-Start:
+# Required-Stop:     startsecond
+# Default-Start:     S
+# Default-Stop:      6
+### END INIT INFO
+EOF
+
+insertscript startsecond <<'EOF' || true
+### BEGIN INIT INFO
+# Provides:          startsecond
+# Required-Start:    startfirst
+# Required-Stop:
+# Default-Start:     S
+# Default-Stop:      6
+### END INIT INFO
+EOF
+
+(cd $tmpdir && ls *)
+
+test_order S startfirst startsecond
+test_order 6 startsecond startfirst
+
+# Test another fake loop.  This one should work, as it is possible to
+# install the two scripts in sequence because one of the dependencies
+# are optional.  It does not with insserv today.
+rm -rf $initddir
+mkdir -p $initddir
+
+insertscript startfirst <<'EOF' || true
+### BEGIN INIT INFO
+# Provides:          startfirst
+# Required-Start:
+# Required-Stop:
+# Should-Stop:       startsecond
+# Default-Start:     S
+# Default-Stop:      6
+### END INIT INFO
+EOF
+
+insertscript startsecond <<'EOF' || true
+### BEGIN INIT INFO
+# Provides:          startsecond
+# Required-Start:    startfirst
+# Required-Stop:
+# Default-Start:     S
+# Default-Stop:      6
+### END INIT INFO
+EOF
+
+(cd $tmpdir && ls *)
+
+# These are checking real bugs, but until bug #458582 is fixed, they
+# will fail.  Making the tests non-fatal because of this.
+test_order S startfirst startsecond
+test_order 6 startsecond startfirst
 
 rm -rf $tmpdir
 
