Import Debian changes 1.11.0-3
insserv (1.11.0-3) unstable; urgency=low

  * Rewrote patch debian/patches/40_segfault_virtprov.dpatch with a
    solution provided by upstream.
  * Added script debian/seq-changes from Frans Pop installed in
    /usr/share/insserv/ to extract the sequence changes done by
    insserv.
  * New testsuite check to detect incorrectly inserted stop symlinks
    when scripts with incorrect headers are encountered.
  * Removed override file for snmptrapfmt, as the package now include
    the LSB header.
  * Removed override file save-etc-disk.  It is not present in Debian.
  * Update the package description and debconf question text (Closes: #464109).
  * New patch 11_more_warnings to activate more warning flags during
    build.  Obsoletes setting the same flags in debian/rules.
  * New patch 50_sign_warning getting rid of some signed/unsigned
    compare issues.
  * Update test suite to the one provided by Werner Fink.
  * Extended test suite to report status at the end.
  * New patch 32_debug_option to add new option -D to print debug
    output.
  * New patch 33_nosuse_scripts to disable some SUSE specific settings.
  * New patch 51_overwrite_output to improve output when symlinks on
    disk do not match the default-* headers.
  * Added override file for slashem-common.
  * New patch 41_cleansystem to clean the .system file.  Changed rules
    file to make sure it take effect.
  * Change test suite to use /bin/bash, as it uses bash-features.
  * Debconf translations:
    - Added Galician from Jacobo Tarrio (Closes: #465067).
    - Added Vietnamese from Clytie Siddall (Closes: #465437).
    - Added Portugese from Américo Monteiro  (Closes: #465519).
    - Added Finnish from Esko Arajärvi (Closes: #465800).

diff --git a/debian/testsuite-common b/debian/testsuite-common
--- a/debian/testsuite-common
+++ b/debian/testsuite-common
@@ -1,131 +1,306 @@
-#!/bin/sh
+#
+# Common test suite definitions, declarations, and functions
+#
+set -eC
+set +o posix
+unset ${!LC@}
+export LANG=POSIX
 
-set -e
+: ${insserv:=${PWD}/insserv}
+: ${tmpdir:=${PWD}/root}
+: ${initddir:=${tmpdir}/etc/init.d}
+: ${insconf:=${tmpdir}/etc/insserv.conf}
+: ${overridedir:=${tmpdir}/etc/insserv/override}
+: ${issuse=""}
+: ${debug:=""}
 
-tmpdir=`pwd`/testdir
-initddir=$tmpdir/etc/init.d
-
-insserv=`pwd`/insserv
-# Relative to $tmpdir
-insconf=$tmpdir/etc/insserv.conf
-overridedir=$tmpdir/etc/insserv/override
-
-retval=0
+declare -i retval=0
+declare -i checkfailed=0
+declare -i testcount=0
+declare -i testfailed=0
+finish_test ()
+{
+    if test 0 -ne $retval ; then
+        echo "error: $testcount test executed, $checkfailed fatal tests failed, $testfailed nonfatal test failed."
+    else
+        echo "success: $testcount test executed, $testfailed nonfatal tests failed."
+    fi
+    rm -rf ${tmpdir}
+    return $retval
+}
+trap 'finish_test' EXIT
 
 mkdir -p $initddir
 
-#debug="-v"
+if test -n "${issuse}" ; then
+    runlevel_path ()
+    {
+	local -a level=($@)
+	level=(${level[@]/%s/S})
+	level=(${level[@]/#/rc})
+	level=(${level[@]/rc[bB]*/boot})
+	printf "${initddir}/%s.d\n" ${level[@]}
+    }
+    list_rclinks()
+    {
+	pushd $initddir/ &> /dev/null
+	echo ${initddir##*/}:
+	ls ${1+"$@"} *
+	popd &> /dev/null
+    }
+    cat <<-'EOF' > $insconf
+	$local_fs	boot.localfs +boot.crypto
+	$network	network
+	$named		+named +dnsmasq +lwresd $network
+	$remote_fs	$local_fs +nfs +smbfs
+	$syslog		syslog
+	$portmap	portmap
+	$time		boot.clock +ntp
+	<interactive>	boot.crypto boot.clock boot.localfs boot.rootfsck apache apache2 kdump ntp
+	EOF
+else
+    runlevel_path ()
+    {
+	printf "${initddir}/../rc%s.d\n" ${1+"$@"}
+    }
+    list_rclinks()
+    {
+	pushd $initddir/../ &> /dev/null
+	ls ${1+"$@"} *
+	popd &> /dev/null
+    }
+    cat <<-'EOF' > $insconf
+	$local_fs	+mountall +umountfs
+	$network	+networking +ifupdown
+	$named		+named +dnsmasq +lwresd +bind9 $network
+	$remote_fs	$local_fs +mountnfs +mountnfs-bootclean +umountnfs +sendsigs
+	$syslog		+syslog +sysklogd
+	$portmap	portmap
+	$time		hwclock
+	<interactive>	udev mountdevsubfs checkroot checkfs console-screen
+	EOF
+fi
+chmod u+w,a+r $insconf
 
-# The specific test suites need to define runlevel_path(),
-# list_rclinks() and insserv_reg().
+insserv_reg ()
+{
+    script=$(printf "${initddir}/%s\n" ${1+"$@"})
+    $insserv $debug -c $insconf -p $initddir -o $overridedir $script
+}
 
-error() {
+insserv_del ()
+{
+    script=$(printf "${initddir}/%s\n" ${1+"$@"})
+    $insserv $debug -c $insconf -p $initddir -o $overridedir -r $script
+}
+
+relpath ()
+{
+    local OLDIFS IFS
+    local -a orgwords
+    local -a locwords
+    local -i relp=0
+    local -i deep=0
+    local p l
+    local path=""
+
+    OLDIFS="$IFS"; IFS=/
+    eval orgwords=(${1// /\\\\ }) ; shift
+    eval locwords=(${1// /\\\\ }) ; shift
+    IFS="$OLDIFS"
+    unset OLDIFS
+
+    deep=0
+    relp=0
+    for l in "${locwords[@]}" ; do
+        if test "$l" = ".." ; then
+	    ((deep++))
+	    continue
+	elif test $deep -gt 0 ; then
+	    while ((deep-- > 0)) ; do
+		unset locwords[$((relp+deep))]
+		(((relp-1)-deep < 0)) || unset locwords[$(((relp-1)-deep))]
+	    done
+	    continue
+        fi
+	((relp++))
+    done
+    locwords=(${locwords[@]})
+
+    deep=0
+    relp=0
+    for p in "${orgwords[@]}" ; do
+	if test "$p" = ".." ; then
+	    ((deep++))
+	    continue
+	elif test $deep -gt 0 ; then
+	    while ((deep-- > 0)) ; do
+		unset orgwords[$((relp+deep))]
+		(((relp-1)-deep < 0)) || unset orgwords[$(((relp-1)-deep))]
+	    done
+	    continue
+	fi
+	((relp++))
+    done
+    orgwords=(${orgwords[@]})
+
+    deep=0
+    relp=0
+    for p in "${orgwords[@]}" ; do
+	eval l="\${locwords[$((deep++))]}"
+	if test "$l" != "$p" -o $relp -ne 0 ; then
+	    ((relp++))
+	    path="${path}/$p"
+	    test -n "$l" || continue
+		if test $relp -eq 1 ; then
+		    path="..${path}"
+		else
+		    path="../${path}"
+		fi
+	 fi
+    done
+    unset orgwords p l
+
+    if test $deep -lt ${#locwords[@]} ; then
+	relp=0
+	while test $relp -lt $deep; do
+	    unset locwords[$((relp++))]
+	done
+	while test ${#locwords[@]} -gt 0  ; do
+	    path="../${path}"
+	    unset locwords[$((relp++))]
+	done
+    fi
+
+    echo "$path"
+}
+
+counttest ()
+{
+    testcount=$(expr $testcount + 1)
+}
+
+error ()
+{
     echo error: $@
+    checkfailed=$(expr $checkfailed + 1)
     retval=1
 }
 
-warning() {
+warning ()
+{
     echo warning: $@
+    testfailed=$(expr $testfailed + 1)
 }
 
-addscript() {
-    scriptname=$1
-    script=$initddir/$scriptname
+addscript ()
+{
+    local scriptname=$1
+    local script=${initddir}/$scriptname
     cat > $script
-    chmod a+rx $script
+    chmod u+w,a+rx $script
 }
 
-insertscript() {
-    scriptname=$1
-    addscript $scriptname
+insertscript ()
+{
+    local scriptname=$1
+    addscript   $scriptname
     insserv_reg $scriptname
 }
 
-present_ok() {
-    runlevel=$1
-    script=$2
-    present="$(echo $(cd $(runlevel_path $runlevel); ls *$script 2>/dev/null) )"
-    if [ "$present" ] ; then
-	return 0
-    fi
-    return 1
+present_ok ()
+{
+    local rcdpath=$(runlevel_path $1); shift
+    local script=$1;   shift
+    local ret=0
+    test -L ${rcdpath}/[KS][0-9][0-9]$script || ret=1
+    counttest
+    return $ret
 }
 
-check_script_present() {
-    runlevel=$1
-    script=$2
-    if present_ok $runlevel $script ; then
-	return 0
-    fi
+check_script_present ()
+{
+    local runlevel=$1; shift
+    local script=$1;   shift
+    present_ok $runlevel $script && return 0
     error "script $script not present in runlevel $runlevel"
-    return 0
 }
 
-test_script_present() {
-    runlevel=$1
-    script=$2
-    if present_ok $runlevel $script ; then
-	return 0
-    fi
+test_script_present ()
+{
+    local runlevel=$1; shift
+    local script=$1;   shift
+    present_ok $runlevel $script && return 0
     warning "script $script not present in runlevel $runlevel"
-    return 0
 }
 
-check_script_not_present() {
-    runlevel=$1
-    script=$2
+check_script_not_present ()
+{
+    local runlevel=$1; shift
+    local script=$1;   shift
     if present_ok $runlevel $script ; then
 	error "script $script present in runlevel $runlevel"
-	return 0
     fi
-    return 0;
+    return 0
 }
 
-test_script_not_present() {
-    runlevel=$1
-    script=$2
+test_script_not_present ()
+{
+    local runlevel=$1; shift
+    local script=$1;   shift
     if present_ok $runlevel $script ; then
 	warning "script $script present in runlevel $runlevel"
-	return 0
     fi
-    return 0;
+    return 0
 }
 
-order_ok() {
-    runlevel=$1
-    script1=$2
-    script2=$3
-    order="$(echo $(cd $(runlevel_path $runlevel); ls *$script1 *$script2 2>/dev/null | sed 's/[SK]..//') )"
-    if [ "$order" != "$script1 $script2" ] ; then
-	return 0
+order_ok ()
+{
+    local rcdpath=$(runlevel_path $1); shift
+    local script1=$1;  shift
+    local script2=$1;  shift
+    local ret=0 scr order=""
+    pushd $rcdpath &> /dev/null
+    if test -n "${issuse}" ; then
+	for scr in S[0-9][0-9]* ; do
+	    test -e "${scr}" || continue
+	    test -L "${scr}" || continue
+	    case "${scr#S[0-9][0-9]}" in
+	    ${script1}) order="${order:+$order }${script1}" ;;
+	    ${script2}) order="${order:+$order }${script2}" ;;
+	    esac
+	done
+    else
+	for scr in [SK][0-9][0-9]* ; do
+	    test -e "${scr}" || continue
+	    test -L "${scr}" || continue
+	    case "${scr#[SK][0-9][0-9]}" in
+	    ${script1}) order="${order:+$order }${script1}" ;;
+	    ${script2}) order="${order:+$order }${script2}" ;;
+	    esac
+	done
     fi
-    return 1;
+    popd &> /dev/null
+    test "$order" = "$script1 $script2" || ret=1
+    counttest
+    return $ret
 }
 
 # Fatal check
-check_order() {
-    if order_ok $@ ; then
-	error "incorrect $runlevel sequence $script1 not before $script2"
-    fi
+check_order ()
+{
+    local runlevel=$1
+    local script1=$2
+    local script2=$3
+    order_ok ${1+"$@"} || error   "incorrect $runlevel sequence $script1 not before $script2" || true
 }
 
 # Non-fatal check
-test_order() {
-    if order_ok $@ ; then
-	warning "incorrect $runlevel sequence $script1 not before $script2"
-    fi
+test_order ()
+{
+    local runlevel=$1
+    local script1=$2
+    local script2=$3
+    order_ok ${1+"$@"} || warning "incorrect $runlevel sequence $script1 not before $script2" || true
 }
 
-finish_test() {
-    if [ 0 != $retval ] ; then
-	echo "error: one or more test failed."
-    else
-	echo "success: no test failed."
-    fi
-    exit $retval
-}
-
-on_exit() {
-    rm -rf $tmpdir
-}
-trap on_exit EXIT # Enable cleanup handler
