Import Debian changes 1.11.0-6
insserv (1.11.0-6) unstable; urgency=low

  [ Petter Reinholdtsen ]
  * Added override files for at, fiaif, gom, ifupdown-scripts-zg2 and tspc.
  * Correct typo in override file for lvm2.
  * Changed postinst and update-bootsystem-insserv to remove the
    generated files /etc/init.d/.depend.* when disabled or removed.
  * Implemented better support in check-initd-orderfor graphing $all
    relations.
  * Restructure update-bootsystem-insserv slightly to make it possible
    to check if it is safe to convert to dependency based boot
    sequencing without doing the conversion.
  * Updated 31_debian_conf to list glibc, hostname and keymap as interactive
    scripts, as none of them can use a pseudoterminal.
  * Add two new tests to verify that x-start-before and x-stop-after
    work as they should.
  * Debconf translations:
    - Added Spanish from Steve Lord Flaubert (Closes: #467391).
    - Added German from Erik Schanze (Closes: #467483).
    - Added Dutch from Bart Cornelis (Closes: #467418).

  [ Kel Modderman ]
  * Modify debian/insserv.config debconf script to honour a preseeded debconf
    value enabling dependency based boot on first installation only.

diff --git a/debian/update-bootsystem-insserv b/debian/update-bootsystem-insserv
--- a/debian/update-bootsystem-insserv
+++ b/debian/update-bootsystem-insserv
@@ -136,13 +136,17 @@ deactivate_inserv() {
 	regenerate_sysv_sequence
 	rm -f $flagfile
     fi
+
+    # Remove files generated by insserv
+    rm -f /etc/init.d/.depend.boot
+    rm -f /etc/init.d/.depend.start
+    rm -f /etc/init.d/.depend.stop
 }
 
-activate_insserv() {
+is_unsafe_to_activate() {
     # Refuse to convert when there are obsolete init.d scripts left
     # behind, as these tend to confuse the boot sequence.
     echo "info: Checking if it is safe to convert to dependency based boot."
-    badstate=""
     for package in $(dpkg -S $(find /etc/init.d -type f -perm /+x) \
                      2>/dev/null | cut -d: -f1 | sort -u); do
         obsolete_initscripts=$(dpkg-query -W -f='${Conffiles}\n' $package | \
@@ -151,7 +155,7 @@ activate_insserv() {
             for initscript in $obsolete_initscripts; do
                 if [ -e "$initscript" ]; then
                     echo "error: Obsolete conffile $initscript left behind by package $package"
-                    badstate=1
+                    return 0
                 fi
             done
         fi
@@ -162,17 +166,20 @@ activate_insserv() {
 	echo "error: Problems running insserv:"
 	egrep 'There is a loop between|loop involving service|already provided!|provides system facility' $logfile | sed 's/^/  /'
 	rm $logfile
-	badstate=1
+	return 0
     fi
+    return 1
+}
 
-    if [ 1 = "$badstate" ] ; then
+activate_insserv() {
+    if is_unsafe_to_activate ; then
 	cat <<EOF
 info: Please check out this manually.
 info: Refusing to convert boot sequence until this is fixed
 info: See http://wiki.debian.org/LSBInitScripts/DependencyBasedBoot
 info: for more information on how to solve these issues.  Most likely,
-info: it is a bug in the binary package with the init.d script, and
-info: not with insserv.
+info: it is a bug in the binary package with the init.d script in
+info: question, and not with insserv.
 EOF
 	exit 1
     fi
@@ -200,10 +207,26 @@ EOF
 	/usr/sbin/update-rc.d-insserv
 }
 
-if [ restore = "$1" ] ; then
-    deactivate_inserv
-else
-    activate_insserv
-fi
+case "$1" in
+    enable|'')
+	activate_insserv
+	;;
+    disable|restore)
+	deactivate_inserv
+	;;
+    check)
+	if is_unsafe_to_activate ; then
+	    echo "warning: It is not safe to convert to dependency based boot."
+	    exit 1
+	else
+	    echo "info: It is safe to convert to dependency based boot."
+	    exit 0
+	fi
+	;;
+    *)
+	echo "error: Unknown argument '$1'"
+	exit 1
+	;;
+esac
 
 exit 0
