Import Debian changes 1.09.0-7
insserv (1.09.0-7) unstable; urgency=low

  * Try to make it it easier to disabling the dependency based boot
    sequencing by calling the postinst of all packages with init.d
    scripts to  register the scripts again.
  * Extend check-initd-order to handle the virtual dependecy $all.
  * Reword the debconf question to try to make it clearer and
    easier to understand.
  * Minor cleanup in irqbalance and atd override file, only depend
    on $remote_fs, no need to also depend on $local_fs.
  * Update check-initd-order to use the same default dependencies
    ($remote_fs $syslog) and the same virtual dependencies as insserv
    when generating dotty graphs.
  * Update check-initd-order to draw left-to-right dotty graphs.
    Based on tip from Frans Pop and Trent Buck.
  * Update lvm2 override to stop before umountroot.

diff --git a/debian/update-bootsystem-insserv b/debian/update-bootsystem-insserv
--- a/debian/update-bootsystem-insserv
+++ b/debian/update-bootsystem-insserv
@@ -27,6 +27,33 @@ convert_rc_s_to_k() {
   done
 }
 
+# Recreate sysv boot sequence by calling the postinst for all packages
+# with init.d scripts, to get them to call update-rc.d again.
+regenerate_sysv_sequence() {
+    packages="`dpkg -S /etc/init.d/* 2>/dev/null | cut -d: -f1|sort -u`"
+
+    for p in $packages ; do
+        # Make sure it is installed
+	if dpkg --get-selections $p | grep -qw install ; then
+            # Only fix packages with init.d scripts
+	    if dpkg -L $p | grep -q /etc/init.d/ ; then
+		brokenpackages="$brokenpackages $p"
+	    fi
+	fi
+    done
+
+    # Remove the old sequence
+    find /etc/rc[S0123456].d -type l -print0 | xargs -0 rm
+
+    # As the sysv-rc update-rc.d script do not check dependencies, it
+    # is enough to run through these scripts once.
+    for p in $brokenpackages ; do
+	echo "Running package $p postinst"
+	DEBCONF_FRONTEND=noninteractive	\
+	    /var/lib/dpkg/info/$p.postinst configure < /dev/null || true
+    done
+}
+
 if [ restore = "$1" ] ; then
     if [ ! -f $flagfile ] ; then
 	echo "error: The boot system is not currently converted to insserv."
@@ -63,7 +90,8 @@ if [ restore = "$1" ] ; then
     else
 	rm "$logdir/current.list"
 	echo "error: Unable to restore the boot sequence.  Invalid backup."
-	exit 1
+	echo "error: Trying to recover by reconfiguring all packages with init.d scripts."
+	regenerate_sysv_sequence
     fi
 else
     insserv -nv > $logfile 2>&1
