Import Debian changes 1.09.0-9
insserv (1.09.0-9) unstable; urgency=low

  * Removed override file pptpd as the compiled in defaults are better
    than the proposed overrides.
  * Correct override file for laptop-netconf after checking the script
    and the package.
  * Added override file for racoon, and corrected override file for
    setkey, after checking the scripts in the package.
  * Try to make recovery routine more robust by not trying to run
    non-existing postinst scripts, and only run postinst scripts for
    packages with executable scripts in /etc/init.d/.
  * Extended check-initd-order to check optional start dependencies,
    and implement check of the shutdown sequence.
  * Extended to check reverse dependencies too.
  * Changed enabling code to refuse to convert to dependency based
    boot sequence when obsolete init.d scripts are found, as these
    tend to mess up the boot sequence.
  * Changed enabling code to refuse to convert to dependency based
    boot sequence if several scripts provide the same service.
  * Added prerm code to refuse to be removed while enabled, to avoid
    messing up the boot system completely.

diff --git a/debian/update-bootsystem-insserv b/debian/update-bootsystem-insserv
--- a/debian/update-bootsystem-insserv
+++ b/debian/update-bootsystem-insserv
@@ -30,7 +30,7 @@ convert_rc_s_to_k() {
 # Recreate sysv boot sequence by calling the postinst for all packages
 # with init.d scripts, to get them to call update-rc.d again.
 regenerate_sysv_sequence() {
-    packages="`dpkg -S /etc/init.d/* 2>/dev/null | cut -d: -f1|sort -u`"
+    packages="$(dpkg -S $(find /etc/init.d -type f -perm /+x) 2>/dev/null | cut -d: -f1 | sort -u)"
 
     for p in $packages ; do
         # Make sure it is installed
@@ -48,9 +48,13 @@ regenerate_sysv_sequence() {
     # As the sysv-rc update-rc.d script do not check dependencies, it
     # is enough to run through these scripts once.
     for p in $brokenpackages ; do
-	echo "Running package $p postinst"
-	DEBCONF_FRONTEND=noninteractive	\
-	    /var/lib/dpkg/info/$p.postinst configure < /dev/null || true
+	if [ -x /var/lib/dpkg/info/$p.postinst ] ; then
+	    echo "info: running package $p postinst"
+	    DEBCONF_FRONTEND=noninteractive	\
+		/var/lib/dpkg/info/$p.postinst configure < /dev/null || true
+	else
+	    echo "error: package $p got init.d script but no postinst"
+	fi
     done
 }
 
@@ -94,13 +98,31 @@ if [ restore = "$1" ] ; then
 	regenerate_sysv_sequence
     fi
 else
+    # Refuse to convert when there are obsolete init.d scripts left
+    # behind, as these tend to confuse the boot sequence.
+    echo "info: Checking if it is safe to convert to dependency based boot."
+    for package in $(dpkg -S $(find /etc/init.d -type f -perm /+x) \
+                     2>/dev/null | cut -d: -f1 | sort -u); do
+        if dpkg-query -W -f='${Conffiles}' $package | \
+            grep /etc/init.d/ | grep -q obsolete; then
+            echo "error: Obsolete init.d conffile left behind by package $package:"
+            dpkg-query -W -f='${Conffiles}' $package | \
+                grep /etc/init.d/ | grep obsolete | sed 's/^/  /'
+            badstate=1
+        fi
+    done
+
     insserv -nv > $logfile 2>&1
-    if grep -q 'There is a loop between' $logfile ; then
+    if egrep -q 'There is a loop between|already provided!' $logfile ; then
 	echo "error: Problems running insserv:"
-	grep 'There is a loop between' $logfile | sed 's/^/  /'
+	egrep 'There is a loop between|already provided!' $logfile | sed 's/^/  /'
 	echo "info: Please check out this manually."
 	echo "info: Refusing to convert boot sequence until this is fixed"
 	rm $logfile
+	badstate=1
+    fi
+
+    if [ 1 = "$badstate" ] ; then
 	exit 1
     fi
 
